# Generated by Django 6.0.5 on 2026-07-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email_alter_user_is_verified'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teaching_teachers', to='catalog.subject', verbose_name='Subjects'),
        ),
    ]
