# Generated by Django 5.2.6 on 2025-11-28 10:42

import django.contrib.auth.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('activity_type', models.CharField(choices=[('game', 'Game'), ('simulator', 'Simulator')], default='game', max_length=64, verbose_name='Activity type')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Body')),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=16, verbose_name='Level')),
                ('date_in', models.DateField(auto_now_add=True, verbose_name='Date in')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Code')),
                ('order', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Question format',
                'verbose_name_plural': 'Question formats',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('order', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=64, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(max_length=64, verbose_name='First name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/%Y/%m/%d/', verbose_name='Avatar')),
                ('user_role', models.CharField(choices=[('learner', 'Learner'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='learner', max_length=16, verbose_name='User role')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='GameTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('question_limit', models.PositiveSmallIntegerField(default=10, verbose_name='Question limit')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_tasks', to='core.activity', verbose_name='Activity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('questions', models.ManyToManyField(related_name='game_tasks', to='core.question', verbose_name='Questions')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_tasks', to='core.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Game Task',
                'verbose_name_plural': 'Game Tasks',
            },
        ),
        migrations.CreateModel(
            name='GameTaskSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finished', 'Finished')], default='pending', max_length=16, verbose_name='Status')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Duration (minutes)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('game_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.gametask', verbose_name='Game Task')),
            ],
            options={
                'verbose_name': 'Game Task Session',
                'verbose_name_plural': 'Game Task Sessions',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=128, verbose_name='Nickname')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Correct answers')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.gametasksession', verbose_name='Game Task Session')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question', verbose_name='Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Is correct')),
                ('score_delta', models.IntegerField(default=0, verbose_name='Score delta')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Time spent (seconds)')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Answered at')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.participant', verbose_name='Participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Question attempt',
                'verbose_name_plural': 'Question attempts',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='core.questionformat', verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='activity',
            name='question_formats',
            field=models.ManyToManyField(related_name='activities', to='core.questionformat', verbose_name='Question formats'),
        ),
        migrations.CreateModel(
            name='QuestionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Code')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.questionformat', verbose_name='Format')),
            ],
            options={
                'verbose_name': 'Question variant',
                'verbose_name_plural': 'Question variants',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='core.questionvariant', verbose_name='Variant'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_answers', to='core.questionattempt', verbose_name='Question attempt')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='answers', to='core.option', verbose_name='Selected options')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.chapter', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.topic', verbose_name='Topic'),
        ),
        migrations.AddConstraint(
            model_name='questionattempt',
            constraint=models.UniqueConstraint(fields=('participant', 'question'), name='unique_participant_question_result'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('chapter', 'title')},
        ),
    ]
