# Generated by Django 5.2.6 on 2025-10-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('pupil', 'Pupil'), ('teacher', 'Teacher')], default='pupil', max_length=32, verbose_name='Account type'),
        ),
    ]
