# Generated by Django 5.2.6 on 2025-12-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AddField(
            model_name='gametasksession',
            name='pin_code',
            field=models.CharField(editable=False, max_length=8, null=True, unique=True, verbose_name='PIN code'),
        ),
    ]
