# Generated by Django 6.0.5 on 2026-05-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='updated_at',
        ),
    ]
