# Generated by Django 6.0.5 on 2026-06-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chapter_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionVariant',
            new_name='FormatVariant',
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='title',
        ),
        migrations.AddField(
            model_name='grade',
            name='code',
            field=models.SlugField(blank=True, max_length=64, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name'),
        ),
    ]
