# Generated by Django 5.2.6 on 2025-12-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_option_options_gametasksession_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='current_question_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Current question ID'),
        ),
        migrations.AddField(
            model_name='participant',
            name='current_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Current question started at'),
        ),
    ]
