# Generated by Django 5.2.6 on 2025-11-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_topic_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametask',
            name='questions',
        ),
        migrations.CreateModel(
            name='GameTaskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('game_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.gametask', verbose_name='Game Task')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Game Task Question',
                'verbose_name_plural': 'Game Task Questions',
            },
        ),
    ]
