# Generated by Django 6.0.5 on 2026-05-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usersession_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_system',
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Is system'),
        ),
    ]
