# Generated by Django 6.0.5 on 2026-06-14 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_questionvariant_formatvariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='core.grade', verbose_name='Grade'),
        ),
    ]
