# Generated by Django 5.2.6 on 2025-11-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_gametask_questions_gametaskquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametask',
            name='question_limit',
        ),
    ]
