# Generated by Django 5.2.6 on 2025-12-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_participant_current_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_limit',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Question Limit'),
        ),
    ]
