# Generated by Django 6.0.5 on 2026-05-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_role_is_system_userrole_is_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
