# Generated by Django 5.2.6 on 2025-12-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_question_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_limit',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Question Limit (min)'),
        ),
    ]
