# Generated by Django 6.0.5 on 2026-06-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chapter_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='code',
            field=models.SlugField(default=1, max_length=64, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(default=1, max_length=64, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
