# Generated by Django 6.0.5 on 2026-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userrole_role_remove_userrole_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('learner', 'Learner')], default='learner', help_text='Показывает роль пользователя в системе.', max_length=20, verbose_name='Role'),
        ),
    ]
