# Generated by Django 5.2.6 on 2025-11-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_gametask_question_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametask',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16, verbose_name='Status'),
        ),
    ]
