# Generated by Django 6.0.5 on 2026-05-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('learner', 'Learner')], default='learner', help_text="Shows the user's role in the system.", max_length=16, verbose_name='Role'),
        ),
    ]
