# Generated by Django 5.2.6 on 2025-12-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_question_question_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametasksession',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Duration (min)'),
        ),
        migrations.AlterField(
            model_name='gametasksession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished at'),
        ),
        migrations.AlterField(
            model_name='gametasksession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='current_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Current question start time'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_limit',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Question limit (sec)'),
        ),
    ]
