# Generated by Django 5.2.6 on 2025-11-29 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gametask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametask',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_tasks', to='core.activity', verbose_name='Activity'),
        ),
    ]
