# Generated by Django 5.2.6 on 2025-12-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_gametasksession_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='current_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Current question started at'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished at'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started at'),
        ),
    ]
