# Generated by Django 5.2.6 on 2025-11-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_gametask_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametask',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
