# Generated by Django 6.0.5 on 2026-06-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teacher_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('chapter', 'title'), name='unique_active_topic_title_per_chapter'),
        ),
    ]
