# Generated by Django 5.2.6 on 2025-12-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_participant_current_started_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='score_delta',
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
