# Generated by Django 5.2.6 on 2025-12-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_questionattempt_score_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametasksession',
            name='session_limit',
            field=models.CharField(choices=[('limited', 'Limited'), ('limitless', 'Limitless')], default='limited', max_length=16, verbose_name='Session limit'),
        ),
    ]
