# Generated by Django 5.2.6 on 2025-12-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_gametasksession_session_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametasksession',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Duration (sec)'),
        ),
    ]
