# Generated by Django 5.2.6 on 2026-01-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_gametasksession_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='limit',
            field=models.CharField(choices=[('limited', 'Limited'), ('limitless', 'Limitless')], default='limited', max_length=16, verbose_name='Limit'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('game', 'Game'), ('simulator', 'Simulator')], default='game', max_length=16, verbose_name='Activity type'),
        ),
    ]
