# Generated by Django 5.2.6 on 2026-01-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_activity_limit_alter_activity_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='limit',
        ),
        migrations.AddField(
            model_name='activity',
            name='play_mode',
            field=models.CharField(choices=[('speed', 'Speed'), ('classic', 'Classic')], default='speed', max_length=16, verbose_name='Play mode'),
        ),
        migrations.AddField(
            model_name='gametasksession',
            name='play_mode',
            field=models.CharField(choices=[('speed', 'Speed'), ('classic', 'Classic')], default='speed', max_length=16, verbose_name='Play mode'),
        ),
    ]
