# Generated by Django 6.0.5 on 2026-07-13 07:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sys_admin', 'System administrator'), ('director', 'Director'), ('deputy_academic', 'Deputy director (academic)'), ('deputy_upbringing', 'Deputy director (upbringing)'), ('homeroom', 'Homeroom teacher'), ('teacher', 'Subject teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=32), default=list, verbose_name='Roles'),
        ),
    ]
