# Generated by Django 6.0.5 on 2026-07-23 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.TextField(verbose_name='Left item')),
                ('right', models.TextField(verbose_name='Right item')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_pairs', to='catalog.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Match pair',
                'verbose_name_plural': 'Match pairs',
                'ordering': ('order',),
            },
        ),
    ]
