# Generated by Django 5.2.6 on 2025-10-20 12:51

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ('grade',),
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Question type',
                'verbose_name_plural': 'Question types',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('school_type', models.CharField(choices=[('state', 'State'), ('private', 'Private'), ('cozy', 'Cozy')], default='state', max_length=16, verbose_name='Type')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=128, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(max_length=128, verbose_name='First name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='core/models/accounts/users/', verbose_name='Avatar')),
                ('google_avatar', models.URLField(blank=True, null=True, verbose_name='Google avatar')),
                ('role', models.CharField(choices=[('pupil', 'Pupil'), ('teacher', 'Teacher'), ('manager', 'Manager')], default='pupil', max_length=32, verbose_name='Role')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('user_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='generics.class')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='generics.school')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeroom_teacher', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Homeroom teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='generics.school', verbose_name='School')),
                ('user_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_links', to='generics.class', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'School class',
                'verbose_name_plural': 'School classes',
                'unique_together': {('school', 'user_class')},
            },
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_subjects', to='generics.school', verbose_name='School')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_subjects', to='generics.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'School subject',
                'verbose_name_plural': 'School subjects',
                'ordering': ('order',),
                'unique_together': {('school', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('user_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='generics.class', verbose_name='Class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='generics.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ('subject', 'user_class', 'order'),
                'unique_together': {('subject', 'user_class', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='generics.chapter', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ('order',),
                'unique_together': {('chapter', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=16, verbose_name='Level')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='generics.questiontype', verbose_name='Question type')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='generics.topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True, verbose_name='Name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('class_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='generics.class', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Letter',
                'verbose_name_plural': 'Letters',
                'ordering': ('order',),
                'unique_together': {('class_grade', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'teacher'}, related_name='school_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Teachers')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='generics.schoolclass', verbose_name='School class')),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='generics.schoolsubject', verbose_name='School subject')),
            ],
            options={
                'verbose_name': 'Class subject',
                'verbose_name_plural': 'Class subjects',
                'ordering': ('order',),
                'unique_together': {('school_class', 'school_subject')},
            },
        ),
    ]
