# Generated by Django 5.2.6 on 2025-10-27 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='generics.school', verbose_name='School'),
        ),
    ]
