# Generated by Django 5.2.6 on 2025-10-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='letter',
            unique_together=set(),
        ),
    ]
