# Generated by Django 5.2.6 on 2025-11-18 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0002_learner_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontype',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='generics.questiontype', verbose_name='Question type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questiontype',
            name='form',
            field=models.CharField(choices=[('none', 'None'), ('test', 'Test'), ('matching', 'Matching'), ('written', 'Written')], default='none', max_length=16, verbose_name='Form'),
        ),
    ]
