# Generated by Django 5.2.6 on 2025-10-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0002_alter_letter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='name',
            field=models.CharField(max_length=2, verbose_name='Name'),
        ),
    ]
