# Generated by Django 5.2.6 on 2025-10-27 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0002_alter_manager_school'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='schools.schoolclass', verbose_name='School class'),
        ),
    ]
