# Generated by Django 5.2.6 on 2025-10-14 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0002_class_classtype_school_user_user_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='generics.school', verbose_name='School')),
                ('teachers', models.ManyToManyField(limit_choices_to={'user_type': 'teacher'}, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
