# Generated by Django 5.2.6 on 2025-10-14 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0003_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_subjects', to='generics.school', verbose_name='School')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_subjects', to='generics.subject', verbose_name='Subject')),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'teacher'}, related_name='school_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Teachers')),
            ],
            options={
                'verbose_name': 'School subject',
                'verbose_name_plural': 'School subjects',
                'ordering': ('order',),
                'unique_together': {('school', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('user_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='generics.class', verbose_name='Class')),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='generics.schoolsubject', verbose_name='School subject')),
            ],
            options={
                'verbose_name': 'Class subject',
                'verbose_name_plural': 'Class subjects',
                'ordering': ('order',),
                'unique_together': {('user_class', 'school_subject')},
            },
        ),
    ]
