# Generated by Django 5.2.6 on 2025-10-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0003_alter_letter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
