# Generated by Django 5.2.6 on 2025-10-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0003_learner_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
