# Generated by Django 5.2.6 on 2025-11-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0003_remove_questiontype_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='feature',
            field=models.CharField(choices=[('none', 'None'), ('Test features', [('single', 'Single'), ('multiple', 'Multiple')]), ('Matching features', [('col', 'Column'), ('row', 'Row')])], default='none', max_length=16, verbose_name='Feature'),
        ),
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.CharField(choices=[('none', 'None'), ('test', 'Test'), ('matching', 'Matching'), ('written', 'Written')], default='none', max_length=16, verbose_name='Form'),
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
