# Generated by Django 5.2.6 on 2025-10-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0004_alter_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
