# Generated by Django 5.2.6 on 2025-11-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0004_remove_question_question_type_question_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_in',
            field=models.DateField(blank=True, null=True, verbose_name='Date in'),
        ),
    ]
