# Generated by Django 5.2.6 on 2025-10-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0004_remove_subject_teachers_schoolsubject_classsubject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
