# Generated by Django 5.2.6 on 2025-10-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0005_alter_subject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
