# Generated by Django 5.2.6 on 2025-11-18 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0005_question_date_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Question format',
                'verbose_name_plural': 'Question formats',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='question',
            name='form',
        ),
        migrations.AddField(
            model_name='question',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='generics.questionformat'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuestionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Code')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='generics.questionformat', verbose_name='Format')),
            ],
            options={
                'verbose_name': 'Question variant',
                'verbose_name_plural': 'Question variants',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='generics.questionvariant', verbose_name='Variant'),
        ),
    ]
