# Generated by Django 5.2.6 on 2025-10-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0005_game_virtual'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionType',
            new_name='TaskType',
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'verbose_name': 'Task type', 'verbose_name_plural': 'Task types'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='task_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='generics.tasktype', verbose_name='Task type'),
            preserve_default=False,
        ),
    ]
