# Generated by Django 5.2.6 on 2025-11-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0006_questionformat_remove_question_feature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionformat',
            options={'ordering': ('order',), 'verbose_name': 'Question format', 'verbose_name_plural': 'Question formats'},
        ),
        migrations.AlterModelOptions(
            name='questionvariant',
            options={'ordering': ('order',), 'verbose_name': 'Question variant', 'verbose_name_plural': 'Question variants'},
        ),
        migrations.AddField(
            model_name='questionformat',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='questionvariant',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
