# Generated by Django 5.2.6 on 2025-10-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0006_rename_questiontype_tasktype_alter_tasktype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='generics.question', verbose_name='Question')),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Virtual',
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ('order',), 'verbose_name': 'Task type', 'verbose_name_plural': 'Task types'},
        ),
    ]
