# Generated by Django 5.2.6 on 2025-10-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0006_subject_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
    ]
