# Generated by Django 5.2.6 on 2025-10-24 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0006_remove_user_school_remove_user_user_class_learner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('learner', 'Learner'), ('teacher', 'Teacher'), ('manager', 'Manager'), ('admin', 'Admin')], default='learner', max_length=32, verbose_name='User role'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='generics.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='generics.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='generics.school', verbose_name='School'),
        ),
    ]
