# Generated by Django 5.2.6 on 2025-10-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0007_option_delete_game_delete_virtual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is correct'),
        ),
    ]
