# Generated by Django 5.2.6 on 2025-11-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0007_alter_questionformat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
