# Generated by Django 5.2.6 on 2025-10-14 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0007_remove_subject_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('order',), 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.RemoveField(
            model_name='schoolsubject',
            name='teachers',
        ),
        migrations.AddField(
            model_name='classsubject',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'teacher'}, related_name='school_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Teachers'),
        ),
    ]
