# Generated by Django 5.2.6 on 2025-10-14 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0008_alter_subject_options_remove_schoolsubject_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtype',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_types', to='generics.school', verbose_name='School'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='classtype',
            unique_together={('school', 'letter')},
        ),
    ]
