# Generated by Django 5.2.6 on 2025-11-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0008_alter_topic_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('interactive_type', models.CharField(choices=[('game', 'Game'), ('simulator', 'Simulator')], max_length=100, verbose_name='Interactive type')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Interactive',
                'verbose_name_plural': 'Interactive',
                'ordering': ('order',),
            },
        ),
    ]
