# Generated by Django 5.2.6 on 2025-10-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0009_classtype_school_alter_classtype_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('pupil', 'Pupil'), ('teacher', 'Teacher'), ('manager', 'Manager')], default='pupil', max_length=32, verbose_name='Account type'),
        ),
    ]
