# Generated by Django 5.2.6 on 2025-10-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0009_game_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='required_qs',
            field=models.ManyToManyField(related_name='games', to='generics.tasktype', verbose_name='Required questions'),
        ),
        migrations.AddField(
            model_name='virtual',
            name='required_qs',
            field=models.ManyToManyField(related_name='virtuals', to='generics.tasktype', verbose_name='Required questions'),
        ),
    ]
