# Generated by Django 5.2.6 on 2025-11-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0009_interactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactive',
            name='interactive_type',
            field=models.CharField(choices=[('game', 'Game'), ('simulator', 'Simulator')], default='game', max_length=100, verbose_name='Interactive type'),
        ),
    ]
