# Generated by Django 5.2.6 on 2025-11-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0010_game_required_qs_virtual_required_qs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='core/generics/accounts/users/', verbose_name='Avatar'),
        ),
    ]
