# Generated by Django 5.2.6 on 2025-10-15 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0010_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('grade',), 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterUniqueTogether(
            name='classtype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('grade', 'class_type')},
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeroom_teacher', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Homeroom teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='generics.school', verbose_name='School')),
                ('user_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_links', to='generics.class', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'School class',
                'verbose_name_plural': 'School classes',
                'unique_together': {('school', 'user_class')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='generics.schoolclass', verbose_name='School class'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('school_class', 'school_subject')},
        ),
        migrations.RemoveField(
            model_name='classtype',
            name='school',
        ),
        migrations.RemoveField(
            model_name='class',
            name='order',
        ),
        migrations.RemoveField(
            model_name='class',
            name='school',
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='user_class',
        ),
    ]
