# Generated by Django 5.2.6 on 2025-10-27 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/', verbose_name='Logo')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Rating')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='generics.school', verbose_name='School')),
            ],
            options={
                'verbose_name': 'School profile',
                'verbose_name_plural': 'School profiles',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='generics.class', verbose_name='Class')),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='generics.teacher', verbose_name='Homeroom teacher')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_class_letters', to='generics.letter', verbose_name='Letter')),
                ('school_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.schoolprofile', verbose_name='School profile')),
            ],
            options={
                'verbose_name': 'School class',
                'verbose_name_plural': 'School classes',
                'unique_together': {('school_profile', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='generics.subject', verbose_name='Subject')),
                ('teachers', models.ManyToManyField(blank=True, related_name='teaching_subjects', to='generics.teacher', verbose_name='Teachers')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='schools.schoolclass', verbose_name='School class')),
            ],
            options={
                'verbose_name': 'Class subject',
                'verbose_name_plural': 'Class subjects',
                'ordering': ('school_class', 'order'),
                'unique_together': {('school_class', 'subject')},
            },
        ),
    ]
