# Generated by Django 5.2.6 on 2025-11-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsubject',
            options={'ordering': ('school_class', 'subject__order'), 'verbose_name': 'Class subject', 'verbose_name_plural': 'Class subjects'},
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='order',
        ),
    ]
